/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;
import Dao.PaketDAO;
import Dao.PaketDAOImpl;
import Model.Paket;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author fadil
 */
public class DialogCariPaket extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogCariPaket.class.getName());

    /**
     * Creates new form DialogCariMember
     */
    public DialogCariPaket(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        tampilData("");
    }
    
    private void tampilData(String keyword) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Paket");
        model.addColumn("Nama Paket");
        model.addColumn("Harga");
        model.addColumn("Masa Aktif");

        try {
            Dao.PaketDAO dao = new Dao.PaketDAOImpl();
            List<Model.Paket> listPaket = dao.getByName(keyword); // Gunakan method yang sudah ada

            for (Model.Paket p : listPaket) {
                model.addRow(new Object[]{
                    p.getIdPaket(),
                    p.getNamaPaket(),
                    p.getHarga(),
                    p.getMasaAktif() + " Hari"
                });
            }
            tabelPaket.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        namaMember = new javax.swing.JLabel();
        fieldNamaMember = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPaket = new javax.swing.JTable();
        tombolPilih = new javax.swing.JButton();
        tombolBatal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cariDataMember = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cari Member");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(430, 410));

        namaMember.setText("Nama Paket");

        fieldNamaMember.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldNamaMemberKeyReleased(evt);
            }
        });

        tabelPaket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Paket", "Nama Paket", "Harga", "Masa Aktif"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPaketMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelPaket);

        tombolPilih.setText("Pilih");
        tombolPilih.addActionListener(this::tombolPilihActionPerformed);

        tombolBatal.setText("Batal");
        tombolBatal.addActionListener(this::tombolBatalActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(namaMember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldNamaMember))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tombolBatal)
                        .addGap(16, 16, 16)
                        .addComponent(tombolPilih)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaMember)
                    .addComponent(fieldNamaMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolBatal)
                    .addComponent(tombolPilih))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        cariDataMember.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        cariDataMember.setForeground(new java.awt.Color(255, 255, 255));
        cariDataMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cariDataMember.setText("CARI DATA PAKET");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cariDataMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cariDataMember, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolBatalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_tombolBatalActionPerformed

    private void fieldNamaMemberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldNamaMemberKeyReleased
        // TODO add your handling code here:
        String keyword = fieldNamaMember.getText();
        tampilData(keyword);
    }//GEN-LAST:event_fieldNamaMemberKeyReleased

    private void tombolPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolPilihActionPerformed
        // TODO add your handling code here:
        int baris = tabelPaket.getSelectedRow();
        int masaAktif = Integer.parseInt(tabelPaket.getValueAt(baris, 3).toString().replace(" Hari", ""));
        
        java.util.Calendar cal = java.util.Calendar.getInstance();
        cal.add(java.util.Calendar.DAY_OF_YEAR, masaAktif);

        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String tglExp = sdf.format(cal.getTime());

        FormTransaksi.fieldTanggalEXP.setText(tglExp);
        
            if (baris == -1) return;

            String idPaket = tabelPaket.getValueAt(baris, 0).toString();
            String namaPaket = tabelPaket.getValueAt(baris, 1).toString();
            double hargaDouble = Double.parseDouble(tabelPaket.getValueAt(baris, 2).toString());
            java.text.DecimalFormat df = new java.text.DecimalFormat("#"); 
            String hargaBersih = df.format(hargaDouble);
            
            FormTransaksi.fieldIdPaket.setText(idPaket);
            FormTransaksi.fieldNamaPaket.setText(namaPaket);
            FormTransaksi.fieldHargaPaket.setText(hargaBersih);
            FormTransaksi.formatTotalBayar(hargaDouble); 

        this.dispose();
        
    }//GEN-LAST:event_tombolPilihActionPerformed

    private void tabelPaketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPaketMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            tombolPilihActionPerformed(null);
        }
    }//GEN-LAST:event_tabelPaketMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogCariPaket dialog = new DialogCariPaket(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cariDataMember;
    private javax.swing.JTextField fieldNamaMember;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel namaMember;
    private javax.swing.JTable tabelPaket;
    private javax.swing.JButton tombolBatal;
    private javax.swing.JButton tombolPilih;
    // End of variables declaration//GEN-END:variables
}
