/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import Model.Kelas;
import Dao.KelasDAO;
import Dao.KelasDAOImpl;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import Utils.CetakLaporan;
/**
 *
 * @author feria
 */
public class FormKelas extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormKelas.class.getName());

    /**
     * Creates new form Lihat_Kelas
     */
    
    public FormKelas (){
        initComponents();
        tampilData();
        setSize(800, 600);
        setLocationRelativeTo(null);
        spinnerJamMulai.setModel(new SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR_OF_DAY));
        JSpinner.DateEditor editorMulai = new JSpinner.DateEditor(spinnerJamMulai, "HH:mm");
        spinnerJamMulai.setEditor(editorMulai);
        spinnerJamSelesai.setModel(new SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR_OF_DAY));
        JSpinner.DateEditor editorSelesai = new JSpinner.DateEditor(spinnerJamSelesai, "HH:mm");
        spinnerJamSelesai.setEditor(editorSelesai);
    }
    
    private void tampilData() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("ID Kelas"); 
        model.addColumn("Nama Kelas");
        model.addColumn("Instruktur");
        model.addColumn("Hari");
        model.addColumn("Jam Mulai");
        model.addColumn("Jam Selesai");
        model.addColumn("Kapasitas");

        try {
            Dao.KelasDAO dao = new Dao.KelasDAOImpl();
            java.util.List<Model.Kelas> listKelas = dao.getAll("");

            for (Model.Kelas k : listKelas) {
                String jamMulai = k.getJamMulai();
                String jamSelesai = k.getJamSelesai();
                
                if (jamMulai != null && jamMulai.length() >= 5) {
                    jamMulai = jamMulai.substring(0, 5);
                }
                if (jamSelesai != null && jamSelesai.length() >= 5) {
                    jamSelesai = jamSelesai.substring(0, 5);
                }
                
                model.addRow(new Object[]{
                    k.getIdKelas(),
                    k.getNamaKelas(),
                    k.getInstruktur(),
                    k.getHari(),
                    jamMulai,      
                    jamSelesai,    
                    k.getKapasitas()
                });
            }
            tabel.setModel(model);

        } catch (Exception e) {
            System.err.println("Gagal memuat data tabel: " + e.getMessage());
        }
    }
    
    private void resetField() {
    fieldNamaKelas.setText("");
    fieldInstruktur.setText("");
    
    if (boxHari.getItemCount() > 0) {
        boxHari.setSelectedIndex(0); 
    }
    
    spinnerJamMulai.setValue(new java.util.Date());
    spinnerJamSelesai.setValue(new java.util.Date());
    boxHari.setSelectedIndex(-1);
    spinnerKapasitas.setValue(0);
    
    fieldNamaKelas.requestFocus();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        tombol = new javax.swing.JPanel();
        tombolSimpan = new javax.swing.JButton();
        tombolEdit = new javax.swing.JButton();
        tombolHapus = new javax.swing.JButton();
        tombolBersihkan = new javax.swing.JButton();
        tombolCetakLaporan = new javax.swing.JButton();
        formInputDataKelas = new javax.swing.JPanel();
        labelFormInputDataKelas = new javax.swing.JLabel();
        tombolKembali = new javax.swing.JButton();
        textField = new javax.swing.JPanel();
        namaKelas = new javax.swing.JPanel();
        labelNamaKelas = new javax.swing.JLabel();
        fieldNamaKelas = new javax.swing.JTextField();
        hari = new javax.swing.JPanel();
        labelHari = new javax.swing.JLabel();
        boxHari = new javax.swing.JComboBox<>();
        kapasitas = new javax.swing.JPanel();
        labelKapasitas = new javax.swing.JLabel();
        spinnerKapasitas = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        instruktur = new javax.swing.JPanel();
        labelInstruktur = new javax.swing.JLabel();
        fieldInstruktur = new javax.swing.JTextField();
        jamMulai = new javax.swing.JPanel();
        labelJamMulai = new javax.swing.JLabel();
        spinnerJamMulai = new javax.swing.JSpinner();
        jamSelesai = new javax.swing.JPanel();
        labelJamSelesai = new javax.swing.JLabel();
        spinnerJamSelesai = new javax.swing.JSpinner();
        headerKelasFitness = new javax.swing.JPanel();
        kelasFitness = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        tabelDataKelas = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        cariDataKelas = new javax.swing.JPanel();
        fieldCariKelas = new javax.swing.JTextField();
        tombolCari = new javax.swing.JButton();
        labelCariDataKelas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tombolSimpan.setBackground(new java.awt.Color(0, 0, 204));
        tombolSimpan.setForeground(new java.awt.Color(255, 255, 255));
        tombolSimpan.setText("Simpan");
        tombolSimpan.addActionListener(this::tombolSimpanActionPerformed);

        tombolEdit.setBackground(new java.awt.Color(204, 204, 0));
        tombolEdit.setForeground(new java.awt.Color(255, 255, 255));
        tombolEdit.setText("Edit");
        tombolEdit.addActionListener(this::tombolEditActionPerformed);

        tombolHapus.setBackground(new java.awt.Color(255, 0, 51));
        tombolHapus.setForeground(new java.awt.Color(255, 255, 255));
        tombolHapus.setText("Hapus");
        tombolHapus.addActionListener(this::tombolHapusActionPerformed);

        tombolBersihkan.setBackground(new java.awt.Color(153, 153, 153));
        tombolBersihkan.setForeground(new java.awt.Color(255, 255, 255));
        tombolBersihkan.setText("Bersihkan");
        tombolBersihkan.addActionListener(this::tombolBersihkanActionPerformed);

        tombolCetakLaporan.setBackground(new java.awt.Color(0, 153, 51));
        tombolCetakLaporan.setForeground(new java.awt.Color(255, 255, 255));
        tombolCetakLaporan.setText("Cetak Laporan");
        tombolCetakLaporan.addActionListener(this::tombolCetakLaporanActionPerformed);

        javax.swing.GroupLayout tombolLayout = new javax.swing.GroupLayout(tombol);
        tombol.setLayout(tombolLayout);
        tombolLayout.setHorizontalGroup(
            tombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tombolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tombolHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(tombolEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(tombolSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(tombolBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(tombolCetakLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tombolLayout.setVerticalGroup(
            tombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tombolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tombolHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tombolLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tombolSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tombolCetakLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tombolBersihkan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tombolEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        formInputDataKelas.setBackground(new java.awt.Color(204, 204, 255));

        labelFormInputDataKelas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelFormInputDataKelas.setText("FORM INPUT DATA KELAS FITNESS");

        tombolKembali.setBackground(new java.awt.Color(153, 153, 153));
        tombolKembali.setForeground(new java.awt.Color(255, 255, 255));
        tombolKembali.setText("Kembali");
        tombolKembali.addActionListener(this::tombolKembaliActionPerformed);

        javax.swing.GroupLayout formInputDataKelasLayout = new javax.swing.GroupLayout(formInputDataKelas);
        formInputDataKelas.setLayout(formInputDataKelasLayout);
        formInputDataKelasLayout.setHorizontalGroup(
            formInputDataKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formInputDataKelasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tombolKembali)
                .addGap(36, 36, 36)
                .addComponent(labelFormInputDataKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formInputDataKelasLayout.setVerticalGroup(
            formInputDataKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formInputDataKelasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formInputDataKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFormInputDataKelas)
                    .addComponent(tombolKembali))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textField.setBackground(new java.awt.Color(255, 255, 255));

        namaKelas.setOpaque(false);

        labelNamaKelas.setText("Nama Kelas");

        javax.swing.GroupLayout namaKelasLayout = new javax.swing.GroupLayout(namaKelas);
        namaKelas.setLayout(namaKelasLayout);
        namaKelasLayout.setHorizontalGroup(
            namaKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaKelasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNamaKelas, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(fieldNamaKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        namaKelasLayout.setVerticalGroup(
            namaKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaKelasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNamaKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNamaKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        hari.setOpaque(false);

        labelHari.setText("Hari");

        boxHari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu" }));
        boxHari.setSelectedIndex(-1);

        javax.swing.GroupLayout hariLayout = new javax.swing.GroupLayout(hari);
        hari.setLayout(hariLayout);
        hariLayout.setHorizontalGroup(
            hariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hariLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(boxHari, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        hariLayout.setVerticalGroup(
            hariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hariLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHari, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        kapasitas.setOpaque(false);

        labelKapasitas.setText("Kapasitas");

        jLabel1.setText("Orang");

        javax.swing.GroupLayout kapasitasLayout = new javax.swing.GroupLayout(kapasitas);
        kapasitas.setLayout(kapasitasLayout);
        kapasitasLayout.setHorizontalGroup(
            kapasitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kapasitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelKapasitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spinnerKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        kapasitasLayout.setVerticalGroup(
            kapasitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kapasitasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kapasitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKapasitas)
                    .addComponent(spinnerKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        instruktur.setOpaque(false);

        labelInstruktur.setText("Instruktur");

        javax.swing.GroupLayout instrukturLayout = new javax.swing.GroupLayout(instruktur);
        instruktur.setLayout(instrukturLayout);
        instrukturLayout.setHorizontalGroup(
            instrukturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrukturLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelInstruktur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fieldInstruktur, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        instrukturLayout.setVerticalGroup(
            instrukturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrukturLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(instrukturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldInstruktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelInstruktur, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jamMulai.setOpaque(false);

        labelJamMulai.setText("Jam Mulai");

        javax.swing.GroupLayout jamMulaiLayout = new javax.swing.GroupLayout(jamMulai);
        jamMulai.setLayout(jamMulaiLayout);
        jamMulaiLayout.setHorizontalGroup(
            jamMulaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jamMulaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelJamMulai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spinnerJamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jamMulaiLayout.setVerticalGroup(
            jamMulaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jamMulaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jamMulaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerJamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jamSelesai.setOpaque(false);

        labelJamSelesai.setText("Jam Selesai");

        javax.swing.GroupLayout jamSelesaiLayout = new javax.swing.GroupLayout(jamSelesai);
        jamSelesai.setLayout(jamSelesaiLayout);
        jamSelesaiLayout.setHorizontalGroup(
            jamSelesaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jamSelesaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelJamSelesai)
                .addGap(18, 18, 18)
                .addComponent(spinnerJamSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jamSelesaiLayout.setVerticalGroup(
            jamSelesaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jamSelesaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jamSelesaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJamSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerJamSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout textFieldLayout = new javax.swing.GroupLayout(textField);
        textField.setLayout(textFieldLayout);
        textFieldLayout.setHorizontalGroup(
            textFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textFieldLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(textFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namaKelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kapasitas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(textFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jamSelesai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instruktur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jamMulai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        textFieldLayout.setVerticalGroup(
            textFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textFieldLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(textFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(instruktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(textFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(textFieldLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(textFieldLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jamSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        headerKelasFitness.setBackground(new java.awt.Color(51, 0, 255));

        kelasFitness.setBackground(new java.awt.Color(0, 0, 255));
        kelasFitness.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        kelasFitness.setForeground(new java.awt.Color(255, 255, 255));
        kelasFitness.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kelasFitness.setText("KELAS FITNESS");

        javax.swing.GroupLayout headerKelasFitnessLayout = new javax.swing.GroupLayout(headerKelasFitness);
        headerKelasFitness.setLayout(headerKelasFitnessLayout);
        headerKelasFitnessLayout.setHorizontalGroup(
            headerKelasFitnessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kelasFitness, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        headerKelasFitnessLayout.setVerticalGroup(
            headerKelasFitnessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerKelasFitnessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kelasFitness)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(tombol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(textField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formInputDataKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headerKelasFitness, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerKelasFitness, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formInputDataKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tombol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Kelas", "Nama Kelas", "Instruktur", "Hari", "Jam Mulai", "Jam Selesai", "Kapasitas"
            }
        ));
        tabel.setSelectionBackground(new java.awt.Color(102, 102, 255));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        tabelDataKelas.setViewportView(tabel);

        cariDataKelas.setBackground(new java.awt.Color(255, 255, 255));

        tombolCari.setBackground(new java.awt.Color(0, 0, 102));
        tombolCari.setForeground(new java.awt.Color(255, 255, 255));
        tombolCari.setText("Cari");
        tombolCari.addActionListener(this::tombolCariActionPerformed);

        labelCariDataKelas.setText("Cari Data Kelas");

        javax.swing.GroupLayout cariDataKelasLayout = new javax.swing.GroupLayout(cariDataKelas);
        cariDataKelas.setLayout(cariDataKelasLayout);
        cariDataKelasLayout.setHorizontalGroup(
            cariDataKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cariDataKelasLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(labelCariDataKelas)
                .addGap(18, 18, 18)
                .addComponent(fieldCariKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tombolCari)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cariDataKelasLayout.setVerticalGroup(
            cariDataKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cariDataKelasLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(cariDataKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCariKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolCari)
                    .addComponent(labelCariDataKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cariDataKelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabelDataKelas)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(cariDataKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelDataKelas, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolSimpanActionPerformed
        // TODO add your handling code here:
        try {
            
            String namaKelas = fieldNamaKelas.getText();
            String instruktur = fieldInstruktur.getText();
            String hari = boxHari.getSelectedItem().toString(); 

            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
            String jamMulai = sdf.format(spinnerJamMulai.getValue());
            String jamSelesai = sdf.format(spinnerJamSelesai.getValue());

            int kapasitas = (Integer) spinnerKapasitas.getValue();

            if (namaKelas.trim().isEmpty() || instruktur.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama Kelas dan Instruktur tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            Kelas kelasBaru = new Kelas(namaKelas, instruktur, hari, jamMulai, jamSelesai, kapasitas);

            KelasDAO dao = new KelasDAOImpl();
            boolean sukses = dao.insert(kelasBaru);

            if (sukses) {
                JOptionPane.showMessageDialog(this, "Data Kelas berhasil disimpan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            tampilData();
            resetField();

            } else {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan data kelas.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error System", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tombolSimpanActionPerformed

    private void tombolEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolEditActionPerformed
        // TODO add your handling code here:
        try {
            int baris = tabel.getSelectedRow();

            if (baris == -1) {
                JOptionPane.showMessageDialog(this, "Pilih data di tabel terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int idKelas = Integer.parseInt(tabel.getValueAt(baris, 0).toString());
            String namaKelas = fieldNamaKelas.getText();
            String instruktur = fieldInstruktur.getText();
            String hari = boxHari.getSelectedItem().toString();

            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
            String jamMulai = sdf.format(spinnerJamMulai.getValue());
            String jamSelesai = sdf.format(spinnerJamSelesai.getValue());

            int kapasitas = (Integer) spinnerKapasitas.getValue();

            if (namaKelas.trim().isEmpty() || instruktur.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama Kelas dan Instruktur tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Kelas kelasEdit = new Kelas(idKelas, namaKelas, instruktur, hari, jamMulai, jamSelesai, kapasitas);

            KelasDAO dao = new KelasDAOImpl();
            boolean sukses = dao.update(kelasEdit);

            if (sukses) {
                JOptionPane.showMessageDialog(this, "Data Kelas berhasil diubah!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                tampilData();
                resetField();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengubah data kelas.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tombolEditActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        try {
            int baris = tabel.getSelectedRow();

            if (baris != -1) {
                fieldNamaKelas.setText(tabel.getValueAt(baris, 1).toString());
                fieldInstruktur.setText(tabel.getValueAt(baris, 2).toString());
                boxHari.setSelectedItem(tabel.getValueAt(baris, 3).toString());

                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("HH:mm");

                java.util.Date waktuMulai = sdf.parse(tabel.getValueAt(baris, 4).toString());
                spinnerJamMulai.setValue(waktuMulai);

                java.util.Date waktuSelesai = sdf.parse(tabel.getValueAt(baris, 5).toString());
                spinnerJamSelesai.setValue(waktuSelesai);

                int kapasitas = Integer.parseInt(tabel.getValueAt(baris, 6).toString());
                spinnerKapasitas.setValue(kapasitas);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error memuat data: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void tombolBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolBersihkanActionPerformed
        // TODO add your handling code here:
        resetField();
    }//GEN-LAST:event_tombolBersihkanActionPerformed

    private void tombolHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusActionPerformed
        // TODO add your handling code here:
            try {
            int baris = tabel.getSelectedRow();

            if (baris == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Pilih data di tabel yang ingin dihapus terlebih dahulu!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data kelas ini?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE);

            if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {

                int idKelas = Integer.parseInt(tabel.getValueAt(baris, 0).toString());

                Dao.KelasDAO dao = new Dao.KelasDAOImpl();
                boolean sukses = dao.delete(idKelas);

                if (sukses) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Data Kelas berhasil dihapus!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);

                    // Refresh tabel dan kosongkan form
                    tampilData();
                    resetField();
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data kelas.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error System", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tombolHapusActionPerformed

    private void tombolCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCariActionPerformed
        // TODO add your handling code here:
        String keyword = fieldCariKelas.getText();

        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("ID Kelas");
        model.addColumn("Nama Kelas");
        model.addColumn("Instruktur");
        model.addColumn("Hari");
        model.addColumn("Jam Mulai");
        model.addColumn("Jam Selesai");
        model.addColumn("Kapasitas");

        try {
            Dao.KelasDAO dao = new Dao.KelasDAOImpl();
            java.util.List<Model.Kelas> listKelas = dao.getAll(keyword); 

            if (listKelas.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data tidak ditemukan!", "Informasi", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }

            for (Model.Kelas k : listKelas) {
                String jamMulai = k.getJamMulai();
                String jamSelesai = k.getJamSelesai();

                if (jamMulai != null && jamMulai.length() >= 5) jamMulai = jamMulai.substring(0, 5);
                if (jamSelesai != null && jamSelesai.length() >= 5) jamSelesai = jamSelesai.substring(0, 5);

                model.addRow(new Object[]{
                    k.getIdKelas(),
                    k.getNamaKelas(),
                    k.getInstruktur(),
                    k.getHari(),
                    jamMulai,
                    jamSelesai,
                    k.getKapasitas()
                });
            }

            tabel.setModel(model);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error pencarian: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tombolCariActionPerformed

    private void tombolCetakLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCetakLaporanActionPerformed
        // TODO add your handling code here:
        try {
            Utils.CetakLaporan.exportToHTML(tabel, "LaporanKelas");
            JOptionPane.showMessageDialog(this, "Berhasil! Laporan tersimpan di folder 'FitTrack/report/LaporanKelas.html'");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal membuat laporan: " + e.getMessage());
        }
    }//GEN-LAST:event_tombolCetakLaporanActionPerformed

    private void tombolKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKembaliActionPerformed
        // TODO add your handling code here:
        new Dashboard_Utama().setVisible(true);
        dispose();
    }//GEN-LAST:event_tombolKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormKelas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxHari;
    private javax.swing.JPanel cariDataKelas;
    private javax.swing.JTextField fieldCariKelas;
    private javax.swing.JTextField fieldInstruktur;
    private javax.swing.JTextField fieldNamaKelas;
    private javax.swing.JPanel formInputDataKelas;
    private javax.swing.JPanel hari;
    private javax.swing.JPanel headerKelasFitness;
    private javax.swing.JPanel instruktur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jamMulai;
    private javax.swing.JPanel jamSelesai;
    private javax.swing.JPanel kapasitas;
    private javax.swing.JLabel kelasFitness;
    private javax.swing.JLabel labelCariDataKelas;
    private javax.swing.JLabel labelFormInputDataKelas;
    private javax.swing.JLabel labelHari;
    private javax.swing.JLabel labelInstruktur;
    private javax.swing.JLabel labelJamMulai;
    private javax.swing.JLabel labelJamSelesai;
    private javax.swing.JLabel labelKapasitas;
    private javax.swing.JLabel labelNamaKelas;
    private javax.swing.JPanel namaKelas;
    private javax.swing.JSpinner spinnerJamMulai;
    private javax.swing.JSpinner spinnerJamSelesai;
    private javax.swing.JSpinner spinnerKapasitas;
    private javax.swing.JTable tabel;
    private javax.swing.JScrollPane tabelDataKelas;
    private javax.swing.JPanel textField;
    private javax.swing.JPanel tombol;
    private javax.swing.JButton tombolBersihkan;
    private javax.swing.JButton tombolCari;
    private javax.swing.JButton tombolCetakLaporan;
    private javax.swing.JButton tombolEdit;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolKembali;
    private javax.swing.JButton tombolSimpan;
    // End of variables declaration//GEN-END:variables
}
