/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Utils.CetakLaporan;
import java.util.HashMap;
import javax.print.PrintServiceLookup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.FileOutputStream;

/**
 *
 * @author fadil
 */
public class FormTransaksi extends javax.swing.JFrame {
    private Dao.TransaksiDAO dao = new Dao.TransaksiDAOImpl();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTransaksi.class.getName());
    private String idTransaksiTerpilih;
    /**
     * Creates new form transaksi
     */
    public FormTransaksi() {
        initComponents();
        tampilData();
        java.util.Date now = new java.util.Date();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        txtTanggal.setText(sdf.format(now));
        fieldIdMember.setEditable(false);
        fieldNamaMember.setEditable(false);
        fieldIdPaket.setEditable(false);
        fieldNamaPaket.setEditable(false);
        fieldHargaPaket.setEditable(false);
        fieldTanggalEXP.setEditable(false);
    }
        
    public static void formatTotalBayar(double angka) {
        java.text.NumberFormat formatRupiah = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id", "ID"));
        fieldTotalBayar.setText(formatRupiah.format(angka));
    }
    
    public String formatRibuan(double angka) {
        java.text.DecimalFormat df = new java.text.DecimalFormat("#,###");
        return df.format(angka);
    }
    
    private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Transaksi");
        model.addColumn("ID Member");
        model.addColumn("ID Paket");  
        model.addColumn("Member");
        model.addColumn("Paket");     
        model.addColumn("Total");
        model.addColumn("Tgl Bayar");
        model.addColumn("Tgl Exp");
        model.addColumn("Status");

        java.text.DecimalFormat df = new java.text.DecimalFormat("#,###");

        for (Model.Transaksi t : dao.getAll()) {
            model.addRow(new Object[]{
                t.getIdTransaksi(), 
                t.getIdMember(),
                t.getIdPaket(), 
                t.getNamaMember(),    
                t.getNamaPaket(),
                df.format(t.getTotalBayar()),
                t.getTglBayar(),
                t.getTglExp(),
                t.getStatusBayar()    
            });
        }
        tabel.setModel(model);
    }
    
    private void resetField() {
        fieldIdMember.setText("");
        fieldNamaMember.setText("");
        fieldIdPaket.setText("");
        fieldNamaPaket.setText("");
        fieldHargaPaket.setText("");
        fieldTanggalEXP.setText("");
        fieldTotalBayar.setText("Rp0");
        boxStatusBayar.setSelectedIndex(-1);

        java.util.Date now = new java.util.Date();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        txtTanggal.setText(sdf.format(now));
        
        tombolCariMember.setEnabled(true);
        tombolCariPaket.setEnabled(true);
        fieldIdMember.setEditable(true);
        fieldIdPaket.setEditable(true);

        idTransaksiTerpilih = null;

        tombolCariMember.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtNamaMember = new javax.swing.JLabel();
        fieldIdMember = new javax.swing.JTextField();
        fieldNamaMember = new javax.swing.JTextField();
        txtIdMember = new javax.swing.JLabel();
        tombolCariMember = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        txtNamaPaket = new javax.swing.JLabel();
        fieldIdPaket = new javax.swing.JTextField();
        fieldNamaPaket = new javax.swing.JTextField();
        txtIdPaket = new javax.swing.JLabel();
        tombolCariPaket = new javax.swing.JButton();
        txtHargaPaket = new javax.swing.JLabel();
        fieldHargaPaket = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        txtTotalBayar = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        fieldTotalBayar = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        txtTanggalEXP = new javax.swing.JLabel();
        fieldTanggalEXP = new javax.swing.JTextField();
        txtStatusBayar = new javax.swing.JLabel();
        boxStatusBayar = new javax.swing.JComboBox<>();
        tombolSimpan = new javax.swing.JButton();
        tombolEdit = new javax.swing.JButton();
        tombolResetField = new javax.swing.JButton();
        tombolCetakLaporan = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        fieldCariTransaksi = new javax.swing.JTextField();
        tombolCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();

        jMenu6.setText("File");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar2.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRANSAKSI MEMBER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setText("FORM INPUT DATA TRANSAKSI");

        jButton6.setBackground(new java.awt.Color(153, 153, 153));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Kembali");

        jLabel3.setText("Tanggal");

        txtTanggal.setText("tanggal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTanggal)
                .addGap(128, 128, 128))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton6)
                    .addComponent(jLabel3)
                    .addComponent(txtTanggal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setOpaque(false);

        txtNamaMember.setText("Nama Member");

        fieldIdMember.addActionListener(this::fieldIdMemberActionPerformed);

        fieldNamaMember.addActionListener(this::fieldNamaMemberActionPerformed);

        txtIdMember.setText("ID Member");

        tombolCariMember.setBackground(new java.awt.Color(51, 51, 255));
        tombolCariMember.setForeground(new java.awt.Color(255, 255, 255));
        tombolCariMember.setText("Cari Member");
        tombolCariMember.addActionListener(this::tombolCariMemberActionPerformed);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tombolCariMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamaMember)
                            .addComponent(txtIdMember))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldIdMember, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(fieldNamaMember))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdMember)
                    .addComponent(fieldIdMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNamaMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaMember))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(tombolCariMember, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setOpaque(false);

        txtNamaPaket.setText("Nama Paket");

        fieldIdPaket.addActionListener(this::fieldIdPaketActionPerformed);

        fieldNamaPaket.addActionListener(this::fieldNamaPaketActionPerformed);

        txtIdPaket.setText("ID Paket");

        tombolCariPaket.setBackground(new java.awt.Color(51, 51, 255));
        tombolCariPaket.setForeground(new java.awt.Color(255, 255, 255));
        tombolCariPaket.setText("Cari Paket");
        tombolCariPaket.addActionListener(this::tombolCariPaketActionPerformed);

        txtHargaPaket.setText("Harga Paket");

        fieldHargaPaket.addActionListener(this::fieldHargaPaketActionPerformed);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tombolCariPaket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtIdPaket)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldIdPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtNamaPaket)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(fieldNamaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtHargaPaket)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldHargaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdPaket)
                    .addComponent(fieldIdPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNamaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaPaket))
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldHargaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHargaPaket))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(tombolCariPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setOpaque(false);

        txtTotalBayar.setText("Total Bayar");

        fieldTotalBayar.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        fieldTotalBayar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fieldTotalBayar.setText("Rp0");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldTotalBayar, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fieldTotalBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTotalBayar)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(txtTotalBayar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel9.setOpaque(false);

        txtTanggalEXP.setText("Tanggal EXP");

        fieldTanggalEXP.addActionListener(this::fieldTanggalEXPActionPerformed);

        txtStatusBayar.setText("Status Bayar");

        boxStatusBayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UNPAID", "PAID", "EXPIRED" }));
        boxStatusBayar.setSelectedIndex(-1);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTanggalEXP)
                    .addComponent(txtStatusBayar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldTanggalEXP)
                    .addComponent(boxStatusBayar, 0, 200, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStatusBayar)
                    .addComponent(boxStatusBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldTanggalEXP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTanggalEXP))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tombolSimpan.setBackground(new java.awt.Color(0, 0, 204));
        tombolSimpan.setForeground(new java.awt.Color(255, 255, 255));
        tombolSimpan.setText("Simpan");
        tombolSimpan.addActionListener(this::tombolSimpanActionPerformed);

        tombolEdit.setBackground(new java.awt.Color(204, 204, 0));
        tombolEdit.setForeground(new java.awt.Color(255, 255, 255));
        tombolEdit.setText("Edit");
        tombolEdit.addActionListener(this::tombolEditActionPerformed);

        tombolResetField.setBackground(new java.awt.Color(153, 153, 153));
        tombolResetField.setForeground(new java.awt.Color(255, 255, 255));
        tombolResetField.setText("Bersihkan");
        tombolResetField.addActionListener(this::tombolResetFieldActionPerformed);

        tombolCetakLaporan.setBackground(new java.awt.Color(0, 204, 0));
        tombolCetakLaporan.setForeground(new java.awt.Color(255, 255, 255));
        tombolCetakLaporan.setText("Cetak Laporan");
        tombolCetakLaporan.addActionListener(this::tombolCetakLaporanActionPerformed);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Cari Data Transaksi:");

        tombolCari.setBackground(new java.awt.Color(51, 51, 255));
        tombolCari.setForeground(new java.awt.Color(255, 255, 255));
        tombolCari.setText("Cari");
        tombolCari.addActionListener(this::tombolCariActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(fieldCariTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tombolCari, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fieldCariTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolCari))
                .addContainerGap())
        );

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tombolSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tombolEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tombolResetField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tombolCetakLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolResetField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolCetakLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldIdMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIdMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIdMemberActionPerformed

    private void fieldNamaMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNamaMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamaMemberActionPerformed

    private void fieldIdPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIdPaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIdPaketActionPerformed

    private void fieldNamaPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNamaPaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamaPaketActionPerformed

    private void fieldHargaPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHargaPaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHargaPaketActionPerformed

    private void tombolCariMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCariMemberActionPerformed
        // TODO add your handling code here:
        DialogCariMember dialog = new DialogCariMember(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_tombolCariMemberActionPerformed

    private void fieldTanggalEXPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTanggalEXPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTanggalEXPActionPerformed

    private void tombolCariPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCariPaketActionPerformed
        // TODO add your handling code here:
        DialogCariPaket dialog = new DialogCariPaket(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_tombolCariPaketActionPerformed

    private void tombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolSimpanActionPerformed
        // TODO add your handling code here:
        if (fieldIdMember.getText().isEmpty() || fieldIdPaket.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silakan pilih Member dan Paket terlebih dahulu!");
            return;
        }

        try {
            Model.Transaksi t = new Model.Transaksi();
            t.setIdMember(Integer.parseInt(fieldIdMember.getText()));
            t.setIdPaket(Integer.parseInt(fieldIdPaket.getText()));
            t.setTglBayar(txtTanggal.getText()); // Pastikan format YYYY-MM-DD
            t.setTglExp(fieldTanggalEXP.getText());

            String totalMentah = fieldTotalBayar.getText().replaceAll("[^0-9]", "");
            t.setTotalBayar(Double.parseDouble(totalMentah));

            t.setStatusBayar(boxStatusBayar.getSelectedItem().toString());

            dao.insert(t);

            JOptionPane.showMessageDialog(this, "Data Transaksi Berhasil Disimpan!");

            resetField();
            tampilData();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Simpan: " + e.getMessage());
    }
    }//GEN-LAST:event_tombolSimpanActionPerformed

    private void tombolResetFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolResetFieldActionPerformed
        // TODO add your handling code here:
        resetField();
    }//GEN-LAST:event_tombolResetFieldActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        int baris = tabel.getSelectedRow();
            tombolCariMember.setEnabled(false); 
            tombolCariPaket.setEnabled(false);
            fieldIdMember.setEditable(false);
            fieldIdPaket.setEditable(false);

            idTransaksiTerpilih = tabel.getValueAt(baris, 0).toString();

            fieldIdMember.setText(tabel.getValueAt(baris, 1).toString());     
            fieldIdPaket.setText(tabel.getValueAt(baris, 2).toString());       
            fieldNamaMember.setText(tabel.getValueAt(baris, 3).toString());   
            fieldNamaPaket.setText(tabel.getValueAt(baris, 4).toString());    

            String hargaRaw = tabel.getValueAt(baris, 5).toString();

            String hargaBersih = hargaRaw.replaceAll("[^0-9]", "");

            fieldHargaPaket.setText(hargaBersih); 

            double total = Double.parseDouble(hargaBersih);
            formatTotalBayar(total);

            fieldTanggalEXP.setText(tabel.getValueAt(baris, 7).toString());
            boxStatusBayar.setSelectedItem(tabel.getValueAt(baris, 8).toString());
            
            
    }//GEN-LAST:event_tabelMouseClicked

    private void tombolEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolEditActionPerformed
        // TODO add your handling code here:
        if (idTransaksiTerpilih == null || idTransaksiTerpilih.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silakan pilih data dari tabel terlebih dahulu!");
            return;
        }

        try {
            String statusBaru = boxStatusBayar.getSelectedItem().toString();
            dao.updateStatus(Integer.parseInt(idTransaksiTerpilih), statusBaru);

            JOptionPane.showMessageDialog(this, "Status berhasil diupdate!");
            tampilData();
            resetField();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mengupdate status: " + e.getMessage());
        }
    }//GEN-LAST:event_tombolEditActionPerformed

    private void tombolCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCariActionPerformed
        // TODO add your handling code here:
        String keyword = fieldCariTransaksi.getText();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Transaksi");
        model.addColumn("ID Member");
        model.addColumn("ID Paket");
        model.addColumn("Member");
        model.addColumn("Paket");
        model.addColumn("Total");
        model.addColumn("Tgl Bayar");
        model.addColumn("Tgl Exp");
        model.addColumn("Status");

        java.text.NumberFormat formatRupiah = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id", "ID"));

        for (Model.Transaksi t : dao.cari(keyword)) {
            model.addRow(new Object[]{
                t.getIdTransaksi(), 
                t.getIdMember(),
                t.getIdPaket(),
                t.getNamaMember(),
                t.getNamaPaket(),
                formatRupiah.format(t.getTotalBayar()),
                t.getTglBayar(),
                t.getTglExp(),
                t.getStatusBayar()
            });
        }
        tabel.setModel(model);
    }//GEN-LAST:event_tombolCariActionPerformed

    private void tombolCetakLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCetakLaporanActionPerformed
        // TODO add your handling code here:
        try {
            Utils.CetakLaporan.exportToHTML(tabel, "LaporanTransaksi");
            JOptionPane.showMessageDialog(this, "Berhasil! Laporan tersimpan di folder 'FitTrack/report/LaporanTransaksi.html'");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal membuat laporan: " + e.getMessage());
            }
    }//GEN-LAST:event_tombolCetakLaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormTransaksi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxStatusBayar;
    private javax.swing.JTextField fieldCariTransaksi;
    public static javax.swing.JTextField fieldHargaPaket;
    public static javax.swing.JTextField fieldIdMember;
    public static javax.swing.JTextField fieldIdPaket;
    public static javax.swing.JTextField fieldNamaMember;
    public static javax.swing.JTextField fieldNamaPaket;
    public static javax.swing.JTextField fieldTanggalEXP;
    public static javax.swing.JLabel fieldTotalBayar;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    private javax.swing.JButton tombolCari;
    private javax.swing.JButton tombolCariMember;
    private javax.swing.JButton tombolCariPaket;
    private javax.swing.JButton tombolCetakLaporan;
    private javax.swing.JButton tombolEdit;
    private javax.swing.JButton tombolResetField;
    private javax.swing.JButton tombolSimpan;
    private javax.swing.JLabel txtHargaPaket;
    private javax.swing.JLabel txtIdMember;
    private javax.swing.JLabel txtIdPaket;
    private javax.swing.JLabel txtNamaMember;
    private javax.swing.JLabel txtNamaPaket;
    private javax.swing.JLabel txtStatusBayar;
    private javax.swing.JLabel txtTanggal;
    private javax.swing.JLabel txtTanggalEXP;
    private javax.swing.JLabel txtTotalBayar;
    // End of variables declaration//GEN-END:variables
}
