/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.FileWriter;
import java.io.File;
/**
 *
 * @author fadil
 */
public class lihatPaket extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(lihatPaket.class.getName());

    /**
     * Creates new form lihatPaket
     */
    public lihatPaket() {
        initComponents();
        tampilData();
        setSize(800, 600);
        setLocationRelativeTo(null);
    }
    
    public void tampilData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Paket");
    model.addColumn("Nama Paket");
    model.addColumn("Masa Aktif");
    model.addColumn("Harga");
    model.addColumn("Deskripsi");

    try {
        Dao.PaketDAO dao = new Dao.PaketDAOImpl();
        java.util.List<Model.Paket> list = dao.getAll();

        java.util.Locale localeID = new java.util.Locale("id", "ID");
        java.text.NumberFormat formatRupiah = java.text.NumberFormat.getCurrencyInstance(localeID);

        for (Model.Paket p : list) {
            String hargaFormat = formatRupiah.format(p.getHarga());
            String teksMasaAktif;
                if (p.getMasaAktif() == 0) {
                    teksMasaAktif = "Unlimited"; 
                } else {
                    teksMasaAktif = p.getMasaAktif() + " Bulan"; 
                }
            model.addRow(new Object[] {
                p.getIdPaket(),
                p.getNamaPaket(),
                teksMasaAktif,
                hargaFormat,              
                p.getDeskripsi()
            });
        }

        tabelData.setModel(model);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal Menampilkan Data : " + e.getMessage());
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldSearchBar = new javax.swing.JTextField();
        tombolCetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lihat Paket");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setText("Cari Paket");

        fieldSearchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldSearchBarKeyReleased(evt);
            }
        });

        tombolCetak.setText("Cetak Laporan");
        tombolCetak.addActionListener(this::tombolCetakActionPerformed);

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(fieldSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tombolCetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolCetak))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCetakActionPerformed
        // TODO add your handling code here:
        try {
        // 1. Inisialisasi struktur dokumen HTML dan CSS untuk Laporan
        String html = "<html>"
                + "<head>"
                + "<title>Laporan Data Paket Gym</title>"
                + "<style>"
                + "body { font-family: Arial, sans-serif; margin: 20px; }"
                + "table { border-collapse: collapse; width: 100%; margin-top: 20px; }"
                + "th, td { border: 1px solid black; padding: 10px; text-align: left; }"
                + "th { background-color: #f2f2f2; font-weight: bold; }"
                + "h2 { color: #333333; }"
                + "</style>"
                + "</head>"
                + "<body>";

        html += "<h2 align='center'>LAPORAN DATA PAKET GYM</h2>";
        html += "<hr>"; // Menambahkan garis pembatas horizontal di bawah judul
        html += "<table>";
        
        // 2. Membuat Header Tabel HTML berdasarkan kolom tabelData Anda
        html += "<tr>";
        for (int k = 0; k < tabelData.getColumnCount(); k++) {
            html += "<th>" + tabelData.getColumnName(k) + "</th>";
        }
        html += "</tr>";

        // 3. Mengambil baris demi baris data dari tabelData secara dinamis
        for (int i = 0; i < tabelData.getRowCount(); i++) {
            html += "<tr>";
            for (int j = 0; j < tabelData.getColumnCount(); j++) {
                html += "<td>"
                        + tabelData.getValueAt(i, j)
                        + "</td>";
            }
            html += "</tr>";
        }

        html += "</table>";
        html += "</body></html>";

        // 4. Menulis string HTML ke dalam file lokal
        File file = new File("laporan_paket_gym.html");
        FileWriter fw = new FileWriter(file);
        fw.write(html);
        fw.close();

        // 5. Eksekusi perintah untuk membuka browser di sistem operasi Linux Anda
        try {
            // Menggunakan bash -c agar perintah dijalankan di dalam shell Environment Anda
            String[] cmd = {
                "bash", 
                "-c", 
                "Brave-browser \"" + file.getAbsolutePath() + "\" || xdg-open \"" + file.getAbsolutePath() + "\""
            };
            Runtime.getRuntime().exec(cmd);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Gagal membuka browser otomatis, silakan buka file '" + file.getName() + "' secara manual.");
            }

        // 6. Tampilkan notifikasi sukses
        JOptionPane.showMessageDialog(null, 
        "Laporan berhasil dibuat dan sedang dibuka di Browser!", 
        "Cetak Sukses", 
        JOptionPane.INFORMATION_MESSAGE);
            
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,
                "Gagal membuat laporan : "
                + e.getMessage());
    }
    }//GEN-LAST:event_tombolCetakActionPerformed

    private void fieldSearchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldSearchBarKeyReleased
        // TODO add your handling code here:
        String keyword = fieldSearchBar.getText().trim();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Paket");
        model.addColumn("Nama Paket");
        model.addColumn("Masa Aktif"); 
        model.addColumn("Harga");
        model.addColumn("Deskripsi");

        try {
            Dao.PaketDAO dao = new Dao.PaketDAOImpl();
            java.util.List<Model.Paket> list = dao.getByName(keyword); 

            java.util.Locale localeID = new java.util.Locale("id", "ID");
            java.text.NumberFormat formatRupiah = java.text.NumberFormat.getCurrencyInstance(localeID);

            for (Model.Paket p : list) {
                String teksMasaAktif;
                if (p.getMasaAktif() == 0) {
                    teksMasaAktif = "Unlimited";
                } else {
                    teksMasaAktif = p.getMasaAktif() + " Bulan";
                }

                model.addRow(new Object[] {
                    p.getIdPaket(),
                    p.getNamaPaket(),
                    teksMasaAktif, 
                    formatRupiah.format(p.getHarga()),
                    p.getDeskripsi()
                });
            }

            tabelData.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Pencarian Gagal : " + e.getMessage());
        }
    }//GEN-LAST:event_fieldSearchBarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new lihatPaket().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldSearchBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelData;
    private javax.swing.JButton tombolCetak;
    // End of variables declaration//GEN-END:variables
}
